# Generated by Django 4.1.2 on 2022-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m', verbose_name='Фото для карточки: 250*200')),
                ('photo_big', models.ImageField(upload_to='photos_big/%Y/%m', verbose_name='Фото большое: высота 600')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Раздел')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №1')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №3')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №4')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №5')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №6')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №7')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №8')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №9')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №10')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №11')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №12')),
                ('photo_13', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №13')),
                ('photo_14', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №14')),
                ('photo_15', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №15')),
                ('photo_16', models.ImageField(blank=True, upload_to='photos_portfolio/%Y/%m', verbose_name='фото №16')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('price2', models.CharField(blank=True, max_length=100, verbose_name='Цена доп')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
