# Generated by Django 4.1.2 on 2022-11-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='slug',
        ),
    ]
